"""
AI Career Development & Performance Coach
==========================================
A CrewAI multi-agent system that transforms 360-degree feedback into
actionable career development plans.

Agents:
  1. Feedback Analyzer   - Parses and synthesizes multi-source feedback
  2. Learning Recommender - Maps skill gaps to curated learning resources
  3. Plan Generator       - Builds a measurable 90-day development plan
"""

import os
import ssl
import truststore
from dotenv import load_dotenv

# Use the Windows system certificate store (handles corporate proxies)
truststore.inject_into_ssl()

from crewai import Crew, Process

from agents import (
    create_feedback_analyzer,
    create_learning_recommender,
    create_plan_generator,
)
from tasks import (
    create_feedback_analysis_task,
    create_learning_recommendation_task,
    create_development_plan_task,
)

load_dotenv(override=True)


def build_career_coach_crew() -> Crew:
    """Assemble the 3-agent career coaching crew with sequential task pipeline."""

    # --- Agents ---
    feedback_analyzer = create_feedback_analyzer()
    learning_recommender = create_learning_recommender()
    plan_generator = create_plan_generator()

    # --- Tasks (sequential: each task feeds into the next) ---
    analysis_task = create_feedback_analysis_task(feedback_analyzer)
    learning_task = create_learning_recommendation_task(
        learning_recommender, context=[analysis_task]
    )
    plan_task = create_development_plan_task(
        plan_generator, context=[analysis_task, learning_task]
    )

    # --- Crew ---
    crew = Crew(
        agents=[feedback_analyzer, learning_recommender, plan_generator],
        tasks=[analysis_task, learning_task, plan_task],
        process=Process.sequential,
        verbose=True,
    )
    return crew


def main():
    api_key = os.getenv("OPENAI_API_KEY")
    if not api_key:
        print("ERROR: OPENAI_API_KEY not found in environment.")
        print("Create a .env file with: OPENAI_API_KEY=sk-...")
        return

    print("=" * 70)
    print("  AI Career Development & Performance Coach")
    print("  Powered by CrewAI Multi-Agent System")
    print("=" * 70)
    print()
    print("Initializing agents...")
    print("  [1] 360-Degree Feedback Analyst")
    print("  [2] Learning & Development Strategist")
    print("  [3] Career Development Plan Architect")
    print()
    print("Starting analysis pipeline...")
    print("-" * 70)

    crew = build_career_coach_crew()
    result = crew.kickoff()

    print()
    print("=" * 70)
    print("  CAREER DEVELOPMENT PLAN - COMPLETE")
    print("=" * 70)
    print()
    print(result)

    # Save the output
    output_path = "output_development_plan.md"
    with open(output_path, "w", encoding="utf-8") as f:
        f.write("# AI Career Development Plan\n\n")
        f.write("*Generated by AI Career Development & Performance Coach*\n\n")
        f.write("---\n\n")
        f.write(str(result))

    print(f"\nPlan saved to: {output_path}")


if __name__ == "__main__":
    main()
